name: OwnIDSample

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    env:
      CI: false

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
